import "dotenv-flow/config";
import express from "express";
import ExpressWs from "express-ws";
import { handleCall } from "./bridge/handler";
import { loadConfig } from "./config";
import { createLogger } from "./logger";
import { getSupabase } from "./supabase/client";
import { callStatusHandler, twimlHandler } from "./http/twilio-webhooks";

const config = loadConfig();
const logger = createLogger({ svc: "bridge" });
const sb = getSupabase(config.supabaseUrl, config.supabaseServiceRoleKey);

const { app } = ExpressWs(express());

app.use(express.urlencoded({ extended: true }));
app.use(express.json());

app.get("/health", (_req, res) => {
  res.json({ status: "ok", ts: new Date().toISOString() });
});

app.post("/twiml", twimlHandler({ sb, hostname: config.hostname, logger }));
app.post("/call-status", callStatusHandler({ sb, hostname: config.hostname, logger }));

// Twilio media stream WebSocket. The :callId path segment is generated by
// the /twiml handler so each call gets a unique URL.
app.ws("/twilio/ws/:callId", (ws, req) => {
  const callId = String(req.params.callId);
  handleCall({ twilioWs: ws, callId, config, sb, logger }).catch((err) => {
    logger.error("handler.unhandled.error", { callId, err });
    try {
      ws.close();
    } catch {
      // already closed
    }
  });
});

app.listen(config.port, () => {
  logger.info("server.listening", { port: config.port, hostname: config.hostname });
});
