import { createHmac } from "crypto";

// HMAC signing format matches the Python bridge's app/calendar/agent_client.py
// exactly. Both the Vercel dashboard's _auth.ts verifier and the Python signer
// agree on this byte layout:
//
//   payload   = `${shop_id}:${timestamp_ms}`  (UTF-8 string concat)
//   signature = HMAC-SHA256(secret, payload).hex()
//   headers   = {
//     "x-shop-id":            <shop_id>,
//     "x-request-timestamp":  <timestamp_ms as decimal string>,
//     "x-agent-signature":    <hex signature>,
//     "content-type":         "application/json",
//   }
//
// Byte-identity with the Python signer is verified by tests/hmac.test.ts
// against three vectors whose expected outputs were generated by Python's
// hmac.new(...).hexdigest() — NOT by this TypeScript implementation.

export function signPayload(shopId: string, timestampMs: number, secret: string): string {
  const payload = `${shopId}:${timestampMs}`;
  return createHmac("sha256", secret).update(payload, "utf8").digest("hex");
}

export interface SignedHeaders {
  "x-shop-id": string;
  "x-request-timestamp": string;
  "x-agent-signature": string;
  "content-type": "application/json";
}

export function buildSignedHeaders(params: {
  shopId: string;
  secret: string;
  timestampMs?: number;
}): SignedHeaders {
  if (!params.secret) {
    throw new Error("HMAC sign: AGENT_API_SECRET is empty");
  }
  const ts = params.timestampMs ?? Date.now();
  return {
    "x-shop-id": params.shopId,
    "x-request-timestamp": String(ts),
    "x-agent-signature": signPayload(params.shopId, ts, params.secret),
    "content-type": "application/json",
  };
}
