import { describe, it, expect } from "vitest";
import { signPayload, buildSignedHeaders } from "../src/http/hmac";

// All three expected hex values were generated by running the Python signer
// (hmac.new(secret_bytes, payload_bytes, hashlib.sha256).hexdigest()) BEFORE
// the TypeScript implementation existed. This is what guarantees the test is
// actually byte-identical to the Python bridge — the expected values are NOT
// the output of this TypeScript code.
//
// To regenerate (e.g. if you change the test inputs):
//
//   python3 -c "import hmac, hashlib; print(hmac.new(
//       b'<secret>', b'<shop_id>:<ts_ms>', hashlib.sha256).hexdigest())"
//
// The Vercel verifier (dashboard/_auth.ts) and the Python signer
// (app/calendar/agent_client.py) both share this exact byte layout.

describe("HMAC sign — byte-identical to Python", () => {
  it("vector 1: simple ASCII secret + UUID-like shop id + 13-digit timestamp", () => {
    const got = signPayload("test-shop-uuid", 1234567890123, "test-secret");
    const expected = "8f544037623940d3dd7557dc75b17d0b34c1330f00ca95b2fc905a2257c4f56f";
    expect(got).toBe(expected);
  });

  it("vector 2: secret with special characters", () => {
    const got = signPayload(
      "shop_riyaaz_music",
      1731366000000,
      "production-like-secret-with-special-chars-!@#",
    );
    const expected = "c907acc909619af57a1d2cd3c90d951dd79f635b4b2b405a1d5bfcf6b9824fd5";
    expect(got).toBe(expected);
  });

  it("vector 3: single-character secret + payload edge case", () => {
    const got = signPayload("a", 1, "k");
    const expected = "7dacde949d062eadb595213ef17bc6166c758e8c77bdf7aee4653e8e45f57688";
    expect(got).toBe(expected);
  });
});

describe("buildSignedHeaders", () => {
  it("emits all four headers in the Python format", () => {
    const headers = buildSignedHeaders({
      shopId: "test-shop-uuid",
      secret: "test-secret",
      timestampMs: 1234567890123,
    });
    expect(headers["x-shop-id"]).toBe("test-shop-uuid");
    expect(headers["x-request-timestamp"]).toBe("1234567890123");
    expect(headers["x-agent-signature"]).toBe(
      "8f544037623940d3dd7557dc75b17d0b34c1330f00ca95b2fc905a2257c4f56f",
    );
    expect(headers["content-type"]).toBe("application/json");
  });

  it("uses Date.now() when timestampMs omitted", () => {
    const before = Date.now();
    const headers = buildSignedHeaders({ shopId: "s", secret: "k" });
    const after = Date.now();
    const ts = Number(headers["x-request-timestamp"]);
    expect(ts).toBeGreaterThanOrEqual(before);
    expect(ts).toBeLessThanOrEqual(after);
  });

  it("throws when secret is empty", () => {
    expect(() => buildSignedHeaders({ shopId: "s", secret: "" })).toThrow(
      /AGENT_API_SECRET is empty/,
    );
  });
});
